{
'name': "Sales Quota Management",
'summary': "Manage Sales quata",
'description': "Manage sales quota",
'author': "Hajril Malik",
'version': '17.0.1.0.0',
"depends": [
        "sale",
        "product",
        "sale_management"
    ],
"data": [
    "security/ir.model.access.csv",
    "views/quota_category.xml",
    "views/quota_allocation.xml",
    "views/quota_usage.xml",
    "views/product.xml",
    "views/quota_deadline.xml",
    "views/customer_quota.xml",
    "views/customer_quota_report.xml",
    "wizard/quota_batch_wizard.xml", 
    "views/quota_period.xml",    
    "views/quota_over_limit.xml",
    "views/quota_menu.xml",
    "views/sale_order_views.xml",
],
'demo': [],
"installable": True,
'application': False,
'license': 'LGPL-3',
}