{
    'name': 'Sistem Akademik',
    'version': '17.0.1.0.0',
    'summary': 'sistem akademik',
    'description': """  sistem akademik  """,
    'author': 'Hajril',
    'depends': ['base', 'contacts', 'hr'],
    'data': [
        'security/ir.model.access.csv',
        'security/akademik_rule.xml',
        'views/akademik_tahun_view.xml',
        'views/akademik_prodi_view.xml',
        'views/akademik_subject_view.xml',
        'views/akademik_krs_package_view.xml',
        'views/akademik_krs_view.xml',
        'views/mahasiswa_view.xml',
        'views/mahasiswa_s1_view.xml',
        'views/mahasiswa_pasca_view.xml',
        'views/menu.xml',
        'wizard/krs_wizard_view.xml',
    ],
    'installable': True,
    'application': True,
}
